### ISSUE TITLE
交易页面的交互

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#13]
![image](https://user-images.githubusercontent.com/2507027/124399697-c60fa100-dd4f-11eb-8d65-335f8c58ccc5.png)

![image](https://user-images.githubusercontent.com/2507027/124399739-00793e00-dd50-11eb-8ede-9b1ea73b638a.png)

对比图如上。
To do list:
## 层叠页面的交互缺陷
- [ ] 关闭左边对话框时，右边 买入/卖出 窗口依然 active。
- [ ] 还是上述的原因，卖出的时候几乎第一次一定会操作错误导致 panel 失效。
- [x] InputBox 不支持显示默认参数。

## 购买页面
- [x] 选择船只时，显示船只的剩余容量
- [ ] 选择船只后，默认自动填入剩余容量与剩余金币可购买商品数量两者的较大值
- [ ] 不可购买数量为 0 的商品。

## 卖出页面
- [ ] 显示该船货品购买时的平均价格
- [ ] 用绿色和红色区分盈利与亏损
- [x] 默认自动卖出最大数量的商品
- [ ] 不可卖出数量为 0 的商品。

**Comment by timewarpsgh** [comment]
这个你在做是吗？看你的了。

**Comment by lychees** [comment]
https://github.com/timewarpsgh/uw2ol/pull/17

![E)(YE73M~%BN}U@~`NA`T4H](https://user-images.githubusercontent.com/2507027/125327545-d0e0bc00-e375-11eb-841e-09d300cba078.png)
