### ISSUE TITLE
冒险功能的实装

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#14]
![image](https://user-images.githubusercontent.com/2507027/124400165-281dd580-dd53-11eb-8d32-ed94a9431ce4.png)

根据大二的设定，冒险发现物的功能有：
- [ ] 汇报给学者以增加冒险声望。
- [ ] 作为和酒吧女郎的谈资。

目前均未实装。

![image](https://user-images.githubusercontent.com/2507027/124400197-4552a400-dd53-11eb-84f6-0ce1b14d13d7.png)

**Comment by timewarpsgh** [comment]
目前在职业介绍所接冒险任务后，再回职业介绍所报告，会有回报。
目前酒吧女郎信息可以直接询问。已加入request.txt。
