### ISSUE TITLE
补给港口相关。

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#18]
目前 Port 总数 130 个，其中前 100 个是标准港口，后 30 个是补给港口。
虽然 Constant 里有 PORT_COUNT 这一数值，但是实际上代码中依然有 hard code 成 130 的地方。
这种设计使得增加新港口不太方便（例如淡水、那霸、etcs）。

- [ ] 目前无法在补给港口触发剧情
- [ ] 所有补给港口的地图一样

**Comment by timewarpsgh** [comment]
大2也是这样。这个先暂时这样吧。
