### ISSUE TITLE
错误按键导致程序崩溃

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#2]
- 海上按 M 导致程序崩溃。
- 按 ctrl 键、光标键等，event.key 值域超过 ascii 范围导致程序崩溃。
- 在登录页面使用聊天框导致连接丢失。
- 聊天框不支持中文。
- 某些情况下 GUI 未彻底关闭，需要按 esc 才可以在码头移动。

**Comment by timewarpsgh** [comment]
已解决。
