### ISSUE TITLE
中文断行问题

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#3]
![telegram-cloud-photo-size-5-6269256899346148603-x](https://user-images.githubusercontent.com/2507027/124340822-8da28280-dbea-11eb-9543-9a9b5b297dac.jpg)

显然应该先把句子拼起来再断行。

**Comment by timewarpsgh** [comment]
![捕获](https://user-images.githubusercontent.com/40222521/124346024-0d424880-dc0f-11eb-8503-71fd7ce3cc5a.PNG)
我这个怎么是好的？

**Comment by lychees** [comment]
看起來是字體大小的問題，需要 hard-code 到 15。
