### ISSUE TITLE
进入 building 的情况下依然响应在港口中的键盘事件

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#4]
![UX% RBJT3)TTR I($ WH%EX](https://user-images.githubusercontent.com/2507027/124358271-24565a00-dc52-11eb-8a04-70b0927c3e5a.png)

已经在 building 内的情况下，可以按 F 可以重复进入，
按 WASD 会在外面移动。

**Comment by timewarpsgh** [comment]
BUG fixed: can enter building more than once

BUG fixed: can move when in building

**Comment by lychees** [comment]
https://github.com/timewarpsgh/uw2ol/commit/98e6de0f788fb29d64184fe4b5af16a5454f0dc5
