### ISSUE TITLE
features request.

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#7]
- [x] 单挑实装
- [x] 风向与洋流实装（[大2的参考实现](https://github.com/JohanLi/uncharted-waters-2/tree/master/scripts/ships)） 感觉不必拘泥于大2踩格子的移动，直接矢量移动效果绝对会更好
- [x] 季风与洋流 [大4的参考实现](https://tieba.baidu.com/p/3176256991)
- [x] 支持与港口的 npc 对话
- [x] 交易时默认交易量为 max，卖出时显示 delta。
- [x] 更多的角色行走图 [参考](https://tieba.baidu.com/p/5058853143?red_tag=0593751692)
- [x] 可修改角色国籍、出生地
- [x] 跟随系统
- [x] 队伍系统
- [x] 商会系统
- [x] 国家系统

**Comment by timewarpsgh** [comment]
added to requests.txt
