### ISSUE TITLE
NPC 对话与持久化

### ISSUE THREAD

**Issue by lychees** [timewarpsgh/uw2ol#8]
大航海时代 OL 的很多任务交接都是直接发生在港口里，和 NPC 对话完成的，目前 uw2ol 触发事件的方式局限在进入建筑的内部。
和 NPC 实现对话并不困难，麻烦的是目前港口的 NPC、天气、时间等信息是客户端生成的，会产生交互不一致的问题。
最好可以将港口的信息、时间和 NPC 等也存储在服务器端，实现这一 feature 可以更好的扩展 rpg 玩法，也可以为日后实现进一步的岸上探险玩法做准备。

**Comment by timewarpsgh** [comment]
暂时延用建筑内触发吧。NPC对话已加入request.txt。比如碰到NPC，NPC会说点港口有关的信息。
